### PR TITLE
To have attribute improvement + improved test coverage

### LINKED ISSUE #438: toHaveAttribute type checking
Inside of toHaveAttribute the condition is:

```
async function condition(el: WebdriverIO.Element, attribute: string, value: string, options: ExpectWebdriverIO.StringOptions): Promise<any> {
    const attr = await el.getAttribute(attribute)
    if (typeof attr !== 'string') {
        return { result: false, value: attr }
    }

    if (typeof value !== 'string') {
        return { result: true, value: attr }
    }

    return compareText(attr, value, options)
}
```

Which means that a test like this would pass

```
test('success with non-string attribute value as expected', async () => {
        el.getAttribute = jest.fn().mockImplementation((attribute: string) => {
            return "Correct Value"
        })
        const result = await toHaveAttribute(el, "attribute_name", 123, { ignoreCase: true });
        expect(result.pass).toBe(true)
    })
```

Is this the expected behaviour because surely this implies that passing in any non-string value as the expected would result in a success which seems like confusing behaviour to me?

### PR DESCRIPTION
**Pull request by Harry-Liversedge**
* Adds a parameter check to distinguish between toHaveAttribute('attrib')  toHaveAttribute('attrib', 'value')
* Adds test cases for toHaveAttribute
* Updates all matchers that make use of toHaveAttribute
* Adds test cases for all matchers that make use of toHaveAttribute

In support of #2 improving unit test coverage
closes #438

### CODE REVIEW

**Comment by mgrybyk** [comment]
I'd only add tests and avoid refactoring of matchers.

**Comment by Harry-Liversedge** [comment]
That is what I initially was doing I do agree, but in #438 I had noticed that there was an unexpected behaviour whereby if you pass in a non-string it previously would fail this test:

```
test('failure with non-string attribute value as expected', async () =&gt; {            el.getAttribute = jest.fn().mockImplementation((attribute: string) =&gt; {                return "Correct Value"            })            const result = await toHaveAttribute(el, "attribute_name", 123, { ignoreCase: true });            expect(result.pass).toBe(false)        })```

**Review by christian-bromann — APPROVED** [review]
This looks good to me 👍 

@mgrybyk good to merge from your side too?

**Review by mgrybyk — APPROVED** [review]

**Comment by christian-bromann** [comment]
@Harry-Liversedge thanks so much for this contribution!

**Pull request merged**
