### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by TuxedoFish**
Unit tests:
- Add expectAdapter tests
- Adds a series of tests for matchers that weren't being hit very well
- Updates (statement) code coverage from ~84 -> ~93

Code change 
- To test expectAdapter exported 2 named functions, found this was the only way to test those two functions

Individual matchers are still missing some unit tests but I think src/util is probably the next place to look at adding some unit tests? I also managed to update my git config to push from my personal GitHub 🎇

#2

### CODE REVIEW

**Comment by mgrybyk** [comment]
Thanks a lot for dealing with tests!

**Review by mgrybyk — APPROVED** [review]

**Comment by christian-bromann** [comment]
@TuxedoFish mind signing the CLA?

**Comment by TuxedoFish** [comment]
@christian-bromann Signed!

**Comment by christian-bromann** [comment]
Thank you so much for this contribution!

**Pull request merged**
