### PR TITLE
Make sure toBeElementsArrayOfSize doesn't delete passed in array

### PR DESCRIPTION
**Pull request by brickfungus**
Fixes https://github.com/webdriverio/expect-webdriverio/issues/1679

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Comment by christian-bromann** [comment]
It seems like the updates to the Eslint dependencies has caused an issue in the pipeline.

**Comment by brickfungus** [comment]
Okay I'll take a look at that.  I did try structuredClone at one point

**Comment by brickfungus** [comment]
@christian-bromann why is it testing on node v16 when the package.json file has ```"engines": {
    "node": ">=18 || >=20 || >=22"
  }```

**Comment by christian-bromann** [comment]
> why is it testing on node v16 when the package.json file has `"engines": { "node": ">=18 || >=20 || >=22" }`

I recognised that the other day, we have to bump the Node.js versions here.

**Comment by brickfungus** [comment]
I changed the workflow file to drop 16 and add 22.  Didn't think wdio supported node 16 anymore, anyways, but if you want to do something different, let me know

**Review by christian-bromann — APPROVED** [review]
Perfect, thank you! 🙏

**Pull request merged**
