### PR TITLE
Adding default trim for toHaveText and toHaveTextContaining

### PR DESCRIPTION
**Pull request by mathew-jithin**
Following changes are made:

- Made `Trim` default for `toHaveText` and `toHaveTextContaining`.
- Changed unit tests for existing conditions to point to the new changes.

### CODE REVIEW

**Comment by mathew-jithin** [comment]
@mgrybyk Not able to find the failing unit test in the codebase now. Can you help me here in case there is some issue?

**Comment by christian-bromann** [comment]
@mathew-jithin can you update your branch? That should fix the build.

**Comment by mathew-jithin** [comment]
@christian-bromann Done. Updated the branch with the new changes.

**Comment by mathew-jithin** [comment]
@christian-bromann Done! Merged main to my branch. Made necessary changes in code as well.

**Review by christian-bromann — APPROVED** [review]
Thanks, great work! 👍

**Pull request merged**
