### PR TITLE
fix: handle toHaveText when receiving an array of elements

### PR DESCRIPTION
**Pull request by sangcnguyen**
I'm trying to take a stab at this #1555. Could you help me review it?

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Amazing work , thanks so much!

🎉

**Comment by lacell75** [comment]
Thanks for this PR , but toHaveText is not working with `expect.arrayContaining`.
For example, I wish to convert this deprecated API 
```await expect($('div').toHaveTextContaining(['text1', 'text2']);
```
with:
```await expect($('div').toHaveText(expect.arrayContaining(['text1', 'text2'])            );
```

I have this error : 
[chrome 125.0.6422.144 Windows 10 #0-0] Expected: ArrayContaining ["text1", "text2"]
[chrome 125.0.6422.144 Windows 10 #0-0] Received: "text1"

**Comment by christian-bromann** [comment]
@sangcnguyen Let's make sure we can support both use cases.

**Comment by sangcnguyen** [comment]
My hunch is does the code below work? I didn't know the use case of using 'expect.arrayContaining' before, so why do we need it?
```
await expect(await $('div')).toHaveText(['text1', 'text2']); 
```

**Comment by christian-bromann** [comment]
@lacell75 mind providing more details? What do you expect to be asserted when calling
```ts
await expect($('div').toHaveText(expect.arrayContaining(['text1', 'text2']));
```

Do you expect that `text1` and `text2` are text in the `div` element? I also didn't know that `await expect($('div').toHaveTextContaining(['text1', 'text2']);` worked before 🤔

**Comment by RodrigoGambino** [comment]
Hi, I have the same error in toHaveText but using `expect.stringContaining`, for example:

`await expect(currentalias).not.toHaveText(expect.stringContaining(previousalias)); `

currentalias and previousalias are string, but it gives me the error `el.getText is not a function`. 

I have version 8.39.1 of webdriverio

**Comment by christian-bromann** [comment]
@RodrigoGambino can you provide a reproducible example?

**Comment by RodrigoGambino** [comment]
@christian-bromann this is an example:
```typescript
const string1 = "Hello World";
const string2 = "Bye";
await expect(string1).not.toHaveText(expect.stringContaining(string2));
```

**Comment by RodrigoGambino** [comment]
Hello, is there anything new with this error?

**Comment by christian-bromann** [comment]
@RodrigoGambino 

> Hello, is there anything new with this error?

As you know, an issue has been filed in #1555 and help on the bug is appreciated. Please get involved!

**Pull request merged**
