### PR TITLE
network matcher doc

### PR DESCRIPTION
**Pull request by mgrybyk**
- moved API to another doc
- added [`## Network Matchers`](https://github.com/webdriverio/expect-webdriverio/blob/80de1f5d0a911c41e2fd2eb97756fd6d037066d3/docs/API.md#network-matchers) section (please review!)

#185

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Given the following example:

```js
expect(mock).toBeRequestedWith({
    url: 'http://localhost:8080/api/todo',          // [optional] string | function | custom matcher
    method: 'POST',                                 // [optional] string | array
    requestHeaders: { Authorization: 'foo' },       // [optional] object | function | custom matcher
    responseHeaders: { Authorization: 'bar' },      // [optional] object | function | custom matcher
    request: { title: 'foo', description: 'bar' },  // [optional] object | function | custom matcher
    response: { success: true },                    // [optional] object | function | custom matcher
})
```

What is the `request` property suppose to represent here? The request payload or its params? Maybe it is more clear if it is called `requestPayload`.

We can do a separate PR for it. These docs changes look good 👍

**Comment by mgrybyk** [comment]
It represents the request payload.
I can rename it to what you've suggested or to postData according to the puppeteer docs https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#httprequestpostdata

**Comment by christian-bromann** [comment]
@mgrybyk `postData` sounds good to me.

**Comment by mgrybyk** [comment]
https://github.com/webdriverio/expect-webdriverio/pull/208

**Comment by mgrybyk** [comment]
@christian-bromann merged this one because https://github.com/webdriverio/webdriverio/pull/5818 is merged

**Pull request merged**
